@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

########## RETRIEVE ALL USERS ##############
GET http://{{host}}/users HTTP/1.1
############################################

########## RETRIEVE ON USER BY {ID} ########
### 
@idFind = 1
GET http://{{host}}/users/{{idFind}} HTTP/1.1
############################################

########## CREATE ONE NEW USER #############
### 
@name = User #{{$randomInt 1 10000}}
@birthDate = {{$datetime iso8601}}
POST http://localhost:8080/users HTTP/1.1
content-type: {{contentType}}

{
  "username": "{{name}}",
  "birthDate": "{{birthDate}}"
}
############################################

########## DELETE ONE USER #################
### 
@idDel = 10
DELETE http://localhost:8080/users/{{idDel}} HTTP/1.1
content-type: {{contentType}}
############################################